apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wwzuhaly7-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:a14e3c97ecbabc9e26cbae89e677b9922d68f3ab@sha256:9ad44ef00d023c3126fccc17dc0c5c6d7a5a2c73b42932fbf6b7c5eaf5c3b6e1
          name: container-image
